# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-06-03 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital', '0003_auto_20190530_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_bridge',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
