# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-05-30 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_vm_config',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vlab_user',
            name='activation_code',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
