# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Virtual_Machine_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon_location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Virtual_Machines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vital.Course')),
            ],
        ),
    ]
