# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-05-30 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital', '0002_auto_20190530_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlab_user',
            name='activation_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
