# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vital', '0006_auto_20160121_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_image',
            name='reimage_file',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
